/**
 * cc-switch core — pure Codex-catalog → pi-model conversion.
 *
 * Functional core: value in / value out, no IO, no logger, no pi API.
 * Everything a test needs is reachable through `catalogModelsToPiModels`.
 * The imperative shell lives in index.ts (catalog loading, registration,
 * commands).
 */

import type { ProviderModelConfig } from "@earendil-works/pi-coding-agent";

// ── pi thinking levels ──────────────────────────────────────────────────────
// pi treats `xhigh` and `max` as opt-in: they only appear in pi's UI when
// the model's thinkingLevelMap has a non-null entry for them. Levels whose
// map entry is `null` are hidden; omitted entries fall back to pi's default
// mapping, so an exact map must list every level explicitly.
const PI_THINKING_LEVELS = [
  "off",
  "minimal",
  "low",
  "medium",
  "high",
  "xhigh",
  "max",
] as const;
type PiThinkingLevel = (typeof PI_THINKING_LEVELS)[number];

function isPiThinkingLevel(level: string): level is PiThinkingLevel {
  return (PI_THINKING_LEVELS as readonly string[]).includes(level);
}

// ── Boundary DTO ───────────────────────────────────────────────────────────
// Slice of the Codex model catalog generated by cc_switch
// (~/.codex/ais-switch-model-catalog.json) — only the fields the core
// reads. Catalog fields without a pi counterpart (description, priority,
// default_reasoning_level) are intentionally not mapped: pi has no
// per-model default thinking level (users can pin one via settings, e.g.
// "cc-switch-gateway/<id>:high").
export interface CodexModel {
  slug: string;
  display_name: string;
  context_window: number;
  max_context_window: number;
  input_modalities: string[];
  supported_reasoning_levels: Array<{ effort: string; description: string }>;
}

export interface CodexModelCatalog {
  models: CodexModel[];
}

// ── Conversion (functional core) ────────────────────────────────────────────

/**
 * Convert catalog models to pi model configs.
 *
 * Defensive by design: the catalog is external data that arrives through a
 * typed cast, so every field is re-checked at runtime. Entries that cannot
 * produce a registerable pi model (no usable slug) are dropped, and missing
 * optional fields fall back to safe defaults — one malformed catalog entry
 * must not fail the whole provider registration.
 */
export function catalogModelsToPiModels(
  models: CodexModel[],
): ProviderModelConfig[] {
  const result: ProviderModelConfig[] = [];
  for (const entry of models) {
    const model = toPiModel(entry);
    if (model) result.push(model);
  }
  return result;
}

function toPiModel(entry: unknown): ProviderModelConfig | null {
  if (!entry || typeof entry !== "object") return null;
  const m = entry as Partial<CodexModel>;

  const slug = typeof m.slug === "string" ? m.slug.trim() : "";
  if (!slug) return null; // pi requires a non-empty model id

  const name =
    typeof m.display_name === "string" && m.display_name.trim()
      ? m.display_name
      : slug;

  const input: ("text" | "image")[] =
    Array.isArray(m.input_modalities) && m.input_modalities.includes("image")
      ? ["text", "image"]
      : ["text"];

  // Exact thinking-level map: a level is selectable in pi iff the catalog
  // lists it (values are the Codex effort names, identical to pi's own).
  // Unknown catalog levels (e.g. "ultra") are skipped — pi has no such
  // level. This map MUST be attached to the model, otherwise pi treats
  // xhigh/max as unsupported and hides them from the UI.
  const thinkingLevelMap: Partial<Record<PiThinkingLevel, string | null>> = {};
  for (const level of PI_THINKING_LEVELS) thinkingLevelMap[level] = null;
  for (const rl of Array.isArray(m.supported_reasoning_levels)
    ? m.supported_reasoning_levels
    : []) {
    const effort = rl?.effort;
    if (typeof effort === "string" && isPiThinkingLevel(effort)) {
      thinkingLevelMap[effort] = effort;
    }
  }

  return {
    id: slug,
    name,
    reasoning: true,
    thinkingLevelMap,
    input,
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow:
      positiveNumber(m.max_context_window) ||
      positiveNumber(m.context_window) ||
      1048576,
    maxTokens: 131072,
    compat: {
      supportsDeveloperRole: false,
      requiresAssistantAfterToolResult: false,
    },
  };
}

function positiveNumber(value: unknown): number {
  return typeof value === "number" && Number.isFinite(value) && value > 0
    ? value
    : 0;
}
