import fs from "node:fs";
import path from "node:path";

import {
  getSettingsPaths,
  readSettingsFile,
  type SettingsRecord,
  writeSettingsFile,
} from "../../shared/settings.js";
import { resolveFeatureWorkflowSetupTargets } from "./args.js";
import { mergeSettingsWithProfile } from "./settings.js";
import {
  DEFAULT_FEATURE_WORKFLOW_COPY_IGNORED_HOOK,
  escapeTomlBasicString,
  FEATURE_WORKFLOW_WT_TOML_PATH,
  type FeatureWorkflowSetupApplyInput,
  type FeatureWorkflowSetupApplyResult,
  type FeatureWorkflowSetupFileChange,
  isExcludedWorktreeIncludeEntry,
  quoteShellArg,
  resolveHookScriptAbsolutePath,
  resolveUserHomePath,
  toRelativeDisplayPath,
  uniqueStrings,
} from "./shared.js";
import {
  getFeatureWorkflowWorktrunkUserConfigPath,
  upsertManagedWorktrunkUserConfig,
} from "./worktrunk-user-config.js";

const WORKTREE_INCLUDE_HEADER = [
  "# Files to copy between worktrees (must also be gitignored)",
  "# Used by: wt step copy-ignored",
];
const GITIGNORE_REQUIRED_ENTRIES = [
  ".pi/",
  ".config/wt.toml",
  ".worktreeinclude",
] as const;
const WT_TOML_MANAGED_BLOCK_START =
  "# >>> pi-kit feature-workflow setup (managed) >>>";
const WT_TOML_MANAGED_BLOCK_END =
  "# <<< pi-kit feature-workflow setup (managed) <<<";

const serializeSettings = (value: SettingsRecord): string =>
  JSON.stringify(value, null, 2);

function buildWorktreeIncludeContent(
  existingContent: string | null,
  requiredEntries: string[],
): {
  content: string;
  changed: boolean;
  addedEntries: string[];
  removedEntries: string[];
} {
  const normalizedRequiredEntries = requiredEntries.filter(
    (entry) => !isExcludedWorktreeIncludeEntry(entry),
  );

  if (existingContent === null) {
    const lines = [
      ...WORKTREE_INCLUDE_HEADER,
      "",
      ...normalizedRequiredEntries,
    ];
    return {
      content: `${lines.join("\n")}\n`,
      changed: true,
      addedEntries: [...normalizedRequiredEntries],
      removedEntries: [],
    };
  }

  const lines = existingContent.split(/\r?\n/);
  if (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }

  const removedEntries: string[] = [];
  const filteredLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (
      trimmed &&
      !trimmed.startsWith("#") &&
      isExcludedWorktreeIncludeEntry(trimmed)
    ) {
      removedEntries.push(trimmed);
      continue;
    }

    filteredLines.push(line);
  }

  const existingEntries = new Set<string>();
  for (const line of filteredLines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    existingEntries.add(trimmed);
  }

  const missing = normalizedRequiredEntries.filter(
    (entry) => !existingEntries.has(entry),
  );

  if (missing.length === 0 && removedEntries.length === 0) {
    return {
      content: existingContent,
      changed: false,
      addedEntries: [],
      removedEntries: [],
    };
  }

  const next = [...filteredLines];
  if (missing.length > 0) {
    if (next.length > 0 && next[next.length - 1] !== "") {
      next.push("");
    }
    next.push(...missing);
  }

  return {
    content: `${next.join("\n")}\n`,
    changed: true,
    addedEntries: missing,
    removedEntries: uniqueStrings(removedEntries),
  };
}

function normalizeGitignoreEntry(value: string): string {
  return value
    .trim()
    .replace(/^\.\//, "")
    .replace(/^\/+/, "")
    .replace(/\/+$/, "");
}

function buildGitignoreContent(existingContent: string | null): {
  content: string;
  changed: boolean;
  addedEntries: string[];
} {
  const lines = existingContent === null ? [] : existingContent.split(/\r?\n/);
  if (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }

  const existingEntries = new Set(
    lines
      .map((line) => line.trim())
      .filter((line) => line.length > 0 && !line.startsWith("#"))
      .map(normalizeGitignoreEntry),
  );

  const missingEntries = GITIGNORE_REQUIRED_ENTRIES.filter(
    (entry) => !existingEntries.has(normalizeGitignoreEntry(entry)),
  );

  if (missingEntries.length === 0) {
    return {
      content: existingContent ?? "",
      changed: false,
      addedEntries: [],
    };
  }

  const next = [...lines];
  if (next.length > 0 && next[next.length - 1] !== "") {
    next.push("");
  }
  next.push(...missingEntries);

  return {
    content: `${next.join("\n")}\n`,
    changed: true,
    addedEntries: [...missingEntries],
  };
}

function buildSymlinkHookScript(symlinkPaths: string[]): string {
  const paths = uniqueStrings(symlinkPaths);
  const lines: string[] = [
    "#!/bin/sh",
    "set -eu",
    "",
    "# Generated by /feature-setup (pi-kit feature-workflow)",
    'PRIMARY_WORKTREE_PATH="$1"',
    'if [ -z "$PRIMARY_WORKTREE_PATH" ]; then',
    '  echo "[feature-workflow] skip: missing primary worktree path"',
    "  exit 0",
    "fi",
    "",
    "link_shared_path() {",
    '  relative_path="$1"',
    '  source_path="$PRIMARY_WORKTREE_PATH/$relative_path"',
    '  target_path="$relative_path"',
    "",
    '  if [ ! -e "$source_path" ] && [ ! -L "$source_path" ]; then',
    "    return",
    "  fi",
    "",
    '  if [ -L "$target_path" ]; then',
    '    ln -sfn "$source_path" "$target_path"',
    "    return",
    "  fi",
    "",
    '  if [ ! -e "$target_path" ]; then',
    '    ln -s "$source_path" "$target_path"',
    "    return",
    "  fi",
    "",
    '  echo "[feature-workflow] skip: ./$target_path exists and is not a symlink"',
    "}",
    "",
  ];

  for (const symlinkPath of paths) {
    lines.push(`link_shared_path ${quoteShellArg(symlinkPath)}`);
  }

  return `${lines.join("\n")}\n`;
}

function buildManagedWtTomlBlock(
  profile: FeatureWorkflowSetupApplyInput["profile"],
): string {
  const command = `bash "${profile.hook.scriptRelativePath}" '{{ primary_worktree_path }}'`;
  const escapedPreStartKey = escapeTomlBasicString(profile.hook.name);
  const escapedPreStartCommand = escapeTomlBasicString(command);
  const escapedPostStartKey = escapeTomlBasicString(
    DEFAULT_FEATURE_WORKFLOW_COPY_IGNORED_HOOK,
  );
  const escapedPostStartCommand = escapeTomlBasicString("wt step copy-ignored");

  return [
    WT_TOML_MANAGED_BLOCK_START,
    "[pre-start]",
    `"${escapedPreStartKey}" = "${escapedPreStartCommand}"`,
    "",
    "[post-start]",
    `"${escapedPostStartKey}" = "${escapedPostStartCommand}"`,
    WT_TOML_MANAGED_BLOCK_END,
  ].join("\n");
}

function upsertManagedWtTomlBlock(
  existingContent: string | null,
  profile: FeatureWorkflowSetupApplyInput["profile"],
): { content: string; changed: boolean } {
  const nextBlock = buildManagedWtTomlBlock(profile);
  const source = existingContent ?? "";
  const startIndex = source.indexOf(WT_TOML_MANAGED_BLOCK_START);
  const endIndex = source.indexOf(WT_TOML_MANAGED_BLOCK_END);

  if (startIndex >= 0 && endIndex > startIndex) {
    const replacementEnd = endIndex + WT_TOML_MANAGED_BLOCK_END.length;
    const nextContent =
      source.slice(0, startIndex) + nextBlock + source.slice(replacementEnd);
    return {
      content: nextContent,
      changed: nextContent !== source,
    };
  }

  const prefix = source.trimEnd();
  const withSpacing =
    prefix.length > 0 ? `${prefix}\n\n${nextBlock}\n` : `${nextBlock}\n`;
  return {
    content: withSpacing,
    changed: withSpacing !== source,
  };
}

function writeFileIfChanged(absolutePath: string, content: string): boolean {
  const existing = fs.existsSync(absolutePath)
    ? fs.readFileSync(absolutePath, "utf-8")
    : null;

  if (existing === content) {
    return false;
  }

  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, content, "utf-8");
  return true;
}

export function applyFeatureWorkflowSetupProfile(
  input: FeatureWorkflowSetupApplyInput,
): FeatureWorkflowSetupApplyResult {
  const userHomePath = resolveUserHomePath(input.userHomePath);
  const targets = resolveFeatureWorkflowSetupTargets({
    onlyTargets: uniqueStrings(input.targets),
    skipTargets: [],
  });
  const changes: FeatureWorkflowSetupFileChange[] = [];

  if (targets.includes("settings")) {
    const { projectPath } = getSettingsPaths(input.cwd);
    const currentSettings = readSettingsFile(projectPath);
    const nextSettings = mergeSettingsWithProfile(
      currentSettings,
      input.profile,
    );
    const changed =
      serializeSettings(currentSettings) !== serializeSettings(nextSettings);

    if (changed) {
      writeSettingsFile(projectPath, nextSettings);
    }

    changes.push({
      target: "settings",
      path: toRelativeDisplayPath(input.repoRoot, projectPath),
      changed,
      message: changed
        ? "Updated featureWorkflow ignored sync settings"
        : "Settings already contain the required profile defaults",
    });
  }

  if (targets.includes("gitignore")) {
    const gitignorePath = path.join(input.repoRoot, ".gitignore");
    const existingContent = fs.existsSync(gitignorePath)
      ? fs.readFileSync(gitignorePath, "utf-8")
      : null;
    const merged = buildGitignoreContent(existingContent);

    if (merged.changed) {
      fs.mkdirSync(path.dirname(gitignorePath), { recursive: true });
      fs.writeFileSync(gitignorePath, merged.content, "utf-8");
    }

    changes.push({
      target: "gitignore",
      path: toRelativeDisplayPath(input.repoRoot, gitignorePath),
      changed: merged.changed,
      message:
        merged.addedEntries.length > 0
          ? `Added entries: ${merged.addedEntries.join(", ")}`
          : "Required entries already present (.pi/, .config/wt.toml, .worktreeinclude)",
    });
  }

  if (targets.includes("worktreeinclude")) {
    const worktreeIncludePath = path.join(input.repoRoot, ".worktreeinclude");
    const existingContent = fs.existsSync(worktreeIncludePath)
      ? fs.readFileSync(worktreeIncludePath, "utf-8")
      : null;
    const merged = buildWorktreeIncludeContent(
      existingContent,
      input.profile.worktreeIncludeEntries,
    );

    if (merged.changed) {
      fs.mkdirSync(path.dirname(worktreeIncludePath), { recursive: true });
      fs.writeFileSync(worktreeIncludePath, merged.content, "utf-8");
    }

    const updates: string[] = [];
    if (merged.addedEntries.length > 0) {
      updates.push(`Added entries: ${merged.addedEntries.join(", ")}`);
    }
    if (merged.removedEntries.length > 0) {
      updates.push(`Removed entries: ${merged.removedEntries.join(", ")}`);
    }

    changes.push({
      target: "worktreeinclude",
      path: toRelativeDisplayPath(input.repoRoot, worktreeIncludePath),
      changed: merged.changed,
      message:
        updates.length > 0
          ? updates.join("; ")
          : "All profile entries already present",
    });
  }

  if (targets.includes("hook-script")) {
    const scriptPath = resolveHookScriptAbsolutePath(
      input.profile.hook.scriptRelativePath,
      input.repoRoot,
      userHomePath,
    );
    const scriptContent = buildSymlinkHookScript(
      input.profile.hook.symlinkPaths,
    );
    const changed = writeFileIfChanged(scriptPath, scriptContent);

    if (fs.existsSync(scriptPath)) {
      fs.chmodSync(scriptPath, 0o755);
    }

    changes.push({
      target: "hook-script",
      path: toRelativeDisplayPath(input.repoRoot, scriptPath),
      changed,
      message: changed
        ? `Hook script updated for: ${uniqueStrings(input.profile.hook.symlinkPaths).join(", ")}`
        : "Hook script already up to date",
    });
  }

  if (targets.includes("wt-toml")) {
    const wtTomlPath = path.join(input.repoRoot, ".config", "wt.toml");
    const existingContent = fs.existsSync(wtTomlPath)
      ? fs.readFileSync(wtTomlPath, "utf-8")
      : null;
    const merged = upsertManagedWtTomlBlock(existingContent, input.profile);

    if (merged.changed) {
      fs.mkdirSync(path.dirname(wtTomlPath), { recursive: true });
      fs.writeFileSync(wtTomlPath, merged.content, "utf-8");
    }

    changes.push({
      target: "wt-toml",
      path: toRelativeDisplayPath(input.repoRoot, wtTomlPath),
      changed: merged.changed,
      message: merged.changed
        ? `Managed Worktrunk hook block installed/updated (${input.profile.hook.name}, ${DEFAULT_FEATURE_WORKFLOW_COPY_IGNORED_HOOK})`
        : "Managed hook block already up to date",
    });
  }

  if (targets.includes("wt-user-config")) {
    const userConfigPath = getFeatureWorkflowWorktrunkUserConfigPath(
      input.userHomePath,
    );
    const existingContent = fs.existsSync(userConfigPath)
      ? fs.readFileSync(userConfigPath, "utf-8")
      : null;
    const merged = upsertManagedWorktrunkUserConfig(existingContent);

    if (merged.changed) {
      fs.mkdirSync(path.dirname(userConfigPath), { recursive: true });
      fs.writeFileSync(userConfigPath, merged.content, "utf-8");
    }

    changes.push({
      target: "wt-user-config",
      path: toRelativeDisplayPath(input.repoRoot, userConfigPath),
      changed: merged.changed,
      message: merged.changed
        ? "Configured Worktrunk user worktree-path template"
        : "Worktrunk user worktree-path already matches recommended template",
    });
  }

  return {
    profileId: input.profile.id,
    targets,
    changes,
    changedCount: changes.filter((change) => change.changed).length,
  };
}

export function getFeatureWorkflowSetupMissingFiles(
  repoRoot: string,
): string[] {
  const missing: string[] = [];
  const wtTomlPath = path.join(repoRoot, FEATURE_WORKFLOW_WT_TOML_PATH);
  if (!fs.existsSync(wtTomlPath)) {
    missing.push(FEATURE_WORKFLOW_WT_TOML_PATH);
  }
  return missing;
}

export function formatFeatureWorkflowSetupResult(
  result: FeatureWorkflowSetupApplyResult,
): string {
  const lines: string[] = [];
  lines.push(`# Feature workflow setup (${result.profileId})`);
  lines.push("");
  lines.push(`- targets: ${result.targets.join(", ") || "none"}`);
  lines.push(`- changed files: ${result.changedCount}`);
  lines.push("");
  lines.push("## Changes");

  for (const change of result.changes) {
    const status = change.changed ? "updated" : "unchanged";
    lines.push(`- [${status}] ${change.path}`);
    lines.push(`  - ${change.message}`);
  }

  lines.push("");
  lines.push("## Next");
  lines.push(
    "- Run `/feature-start` or `/feature-switch` to verify ignored sync behavior.",
  );

  return `${lines.join("\n")}\n`;
}
